type: object
properties:
  id:
    type: integer
  projectId:
    type: integer
  projectName:
    type: string
  applicant:
    $ref: ./UserVO.yaml
  applyReason:
    type: string
    deprecated: true
    description: 申请理由/留言(已弃用)
  contact:
    type: string
  status:
    $ref: ./ApplicationStatus.yaml
  replyMsg:
    type: string
    deprecated: true
    description: 队长回复(已弃用)
  appliedAt:
    type: string
    format: date-time
