type: object
properties:
  id:
    type: integer
  projectId:
    type: integer
  projectName:
    type: string
  applicant:
    $ref: ./UserVO.yaml
  applyReason:
    type: string
    description: 申请理由/留言
  contact:
    type: string
  status:
    $ref: ./ApplicationStatus.yaml
  replyMsg:
    type: string
    description: 队长回复
  appliedAt:
    type: string
    format: date-time
